--- what is the total revenue generated by male vs female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender; 

--- which customer used a discount but still spent more than avg purchase amount

select customer_id,purchase_amount
from customer
where discount_applied= 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


--- which are the top 5 products with highest average review rating?
select item_purchased , ROUND(AVG(review_rating)) as "Average Product Rating"
from customer
group by item_purchased 
order by avg(review_rating) desc limit 5;



---compare avg purchased amount b/w standard and express shipping
select shipping_type,ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
;
---Do subscribed customers spend more? comp avg & total revenue
---b/w subscribers and non subscriber
select subscription_status , count(customer_id) as total_customers, ROUND(AVG(purchase_amount),2) as avg_spend ,round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;



--- WHICH 5 prod have highest % of purchases with discount applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2)as discount_rate
from customer 
group by item_purchased
order by discount_rate desc	
limit 5;



---Segment customer into New, Returning, and Loyal based on their total number of previous purchase, and show the count of  each segment.

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'NEW'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
            ELSE 'LOYAL'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;




---what are the top 3 most purchased products within each category


with item_counts as(
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category , item_purchased, total_orders
from item_counts
where item_rank <= 3;


---Are customers eho are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
;



---what is the revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;